keys:
  plnates:
    X-RapidAPI-Key: '1ef7713c70mshfdd950e72ee08a7p14f736jsn30b99e581ea4'
    X-RapidAPI-Host: "planets-info-by-newbapi.p.rapidapi.com"
  amazon:
    client-id: amzn1.application-oa2-client.2ee66d0a41a84bd4960286bcc52e9a00
    client-secret: amzn1.oa2-cs.v1.6aeaa10551d4cb357e5420f97b1a21171a4b6139a336e822f126835da6d5b564
  bing-news:
    X-BingApis-SDK: 'true'
    X-RapidAPI-Key: '1ef7713c70mshfdd950e72ee08a7p14f736jsn30b99e581ea4'
    X-RapidAPI-Host: 'bing-news-search1.p.rapidapi.com'

spring:
  boot:
    admin:
      client:
        auto-registration: true
        enabled: true
        url: http://localhost:9000
        instance:
          name: my-clinet-1
  application:
    name: WebFluxSpringApplication
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 1e0a51218126a48f9b39
            clientSecret: 529b727ab82f39ab521ecbc1acf1a109b46e7e3e
  main:
    web-application-type: REACTIVE
  # mvc:
  #   throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: always
#  web:
#    resources:
#      add-mappings: false



management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: loggers
  endpoint:
    loggers:
      enabled: true
server:
  port: 8080
  address: 127.0.0.1


logging:
  file:
    name: "C:/Users/abhis/Documents/workspace-spring-tool-suite-4-4.17.0.RELEASE/ReactiveSpringRouter/logs/app1.log"
    path: "C:/Users/abhis/Documents/workspace-spring-tool-suite-4-4.17.0.RELEASE/ReactiveSpringRouter/logs/"
  level:
#    root: INFO
    com.abhishek: DEBUG
    org.springframework.security: INFO #To print the Security log
#    performance.*: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback.rollingpolicy.max-history: 7
